# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ab4d1f73fc8bf9a312a2aa4513c62dc32a438a2f4bcce6cdfbc82756bab2501470fae6555f0eb280f103eae83a92d7a727cc2b75bd81a4667d16321589d2c03

test:
  secret_key_base: a48279ae74c78847fcfea333456bdd3c95de27dd6601b1ca03dbd22222a84d8c502592d2f4bfc82f421029006ddfa513286f5e2a5ebd1848bb591905d63ec914

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
